org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# NeoForge versions: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.82

# Mod properties
mod_id=examplemod
mod_name=Example Mod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.example.examplemod
mod_authors=YOUR_NAME
mod_description=A multi-loader Minecraft mod.

